"""Add institutional grade fields

Revision ID: 7e113e629e8b
Revises: ff8c1853b757
Create Date: 2026-03-05 15:26:00.900418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e113e629e8b'
down_revision: Union[str, None] = 'ff8c1853b757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
