"""Initial schema

Revision ID: d8df0a1c7db8
Revises: 
Create Date: 2026-03-05 13:38:04.236878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8df0a1c7db8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('bank_code', sa.String(length=10), nullable=True),
    sa.Column('masked_account_number', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.Enum('CHECKING', 'SAVINGS', 'CREDIT_CARD', 'INVESTMENT', name='accounttype'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('card_payment_envelope_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('ENVELOPE_CREATED', 'ENVELOPE_ALLOCATION', 'READY_TO_ASSIGN_RECEIPT', 'CREDIT_PURCHASE_FUNDED', 'CREDIT_PURCHASE_UNFUNDED', 'CREDIT_PURCHASE_POSITIVE', 'CREDIT_INVOICE_PAYMENT', 'INSTALLMENT_GROUP_CREATED', 'SUBSCRIPTION_BILLED', 'SUBSCRIPTION_OVERDUE', 'IDEMPOTENT_IMPORT', 'DUPLICATE_SKIPPED', 'ACCOUNT_DELETION_REQUESTED', 'ACCOUNT_DATA_ERASED', 'SENSITIVE_FIELD_ACCESSED', 'BALANCE_ADJUSTMENT', name='auditeventtype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_audit_events_user_type', ['user_id', 'event_type'], unique=False)

    op.create_table('budget_envelopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('allocated', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('spent', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', 'month', name='uq_envelope_user_name_month')
    )
    with op.batch_alter_table('budget_envelopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_envelopes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_envelopes_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_envelopes_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_envelopes_user_month', ['user_id', 'month'], unique=False)

    op.create_table('installment_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('envelope_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('installment_count', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='installmentgroupstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installment_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installment_groups_id'), ['id'], unique=False)
        batch_op.create_index('ix_installment_groups_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installment_groups_user_id'), ['user_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('debit_envelope_id', sa.String(length=36), nullable=False),
    sa.Column('credit_envelope_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_credit_envelope_id'), ['credit_envelope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_debit_envelope_id'), ['debit_envelope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('PIX', 'CREDIT_CARD', 'DEBIT', 'BOLETO', name='paymentmethod'), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('envelope_id', sa.String(length=36), nullable=False),
    sa.Column('billing_day', sa.Integer(), nullable=False),
    sa.Column('next_billing_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_next_billing_date'), ['next_billing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_subscriptions_user_next_billing', ['user_id', 'next_billing_date'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('transaction_type', sa.Enum('CREDIT', 'DEBIT', 'TRANSFER', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('POSTED', 'PENDING', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('envelope_id', sa.String(length=36), nullable=True),
    sa.Column('funding_state', sa.Enum('FUNDED', 'UNFUNDED', 'POSITIVE', 'INVOICE_PAYMENT', 'NOT_APPLICABLE', name='fundingstate'), nullable=False),
    sa.Column('role', sa.Enum('STANDALONE', 'INSTALLMENT_PARENT', 'INSTALLMENT_CHILD', 'SUBSCRIPTION', name='transactionrole'), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('installment_seq', sa.Integer(), nullable=True),
    sa.Column('installment_total', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('fit_id', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('payee', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_transactions_idempotency')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_envelope_id'), ['envelope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_fit_id'), ['fit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index('ix_transactions_parent', ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index('ix_transactions_user_date', ['user_id', 'date'], unique=False)
        batch_op.create_index('ix_transactions_user_envelope', ['user_id', 'envelope_id'], unique=False)
        batch_op.create_index('ix_transactions_user_fitid', ['user_id', 'fit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data_minimization_level', sa.String(length=20), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(), nullable=True),
    sa.Column('deletion_requested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index('ix_transactions_user_fitid')
        batch_op.drop_index('ix_transactions_user_envelope')
        batch_op.drop_index('ix_transactions_user_date')
        batch_op.drop_index(batch_op.f('ix_transactions_parent_id'))
        batch_op.drop_index('ix_transactions_parent')
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_fit_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_envelope_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_subscriptions_user_next_billing')
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_next_billing_date'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_debit_envelope_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_credit_envelope_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('installment_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installment_groups_user_id'))
        batch_op.drop_index('ix_installment_groups_user')
        batch_op.drop_index(batch_op.f('ix_installment_groups_id'))

    op.drop_table('installment_groups')
    with op.batch_alter_table('budget_envelopes', schema=None) as batch_op:
        batch_op.drop_index('ix_envelopes_user_month')
        batch_op.drop_index(batch_op.f('ix_budget_envelopes_user_id'))
        batch_op.drop_index(batch_op.f('ix_budget_envelopes_month'))
        batch_op.drop_index(batch_op.f('ix_budget_envelopes_id'))

    op.drop_table('budget_envelopes')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_user_type')
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index('ix_audit_events_created')

    op.drop_table('audit_events')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_id'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
