"""Add payment methods and credit card fields

Revision ID: ff8c1853b757
Revises: d8df0a1c7db8
Create Date: 2026-03-05 14:04:22.795377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8c1853b757'
down_revision: Union[str, None] = 'd8df0a1c7db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_due_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invoice_closing_day', sa.Integer(), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('CASH_PIX', 'CREDIT_CARD', 'DEBIT_CARD', 'BOLETO_TRANSFER', 'OTHER', name='paymentmethod'),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.Enum('CASH_PIX', 'CREDIT_CARD', 'DEBIT_CARD', 'BOLETO_TRANSFER', 'OTHER', name='paymentmethod'), nullable=False))
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('recurrence_rule', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('recurrence_rule')
        batch_op.drop_column('is_recurring')
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.Enum('CASH_PIX', 'CREDIT_CARD', 'DEBIT_CARD', 'BOLETO_TRANSFER', 'OTHER', name='paymentmethod'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('invoice_closing_day')
        batch_op.drop_column('invoice_due_day')

    # ### end Alembic commands ###
